### ISSUE TITLE
Fix some of the warnings raised by sass-lint

### ISSUE THREAD

**Issue by katebee** [guardian/commercial-templates#152]
PR #151 introduced [sass-lint](https://github.com/sasstools/sass-lint) to commercial-templates, so all future sass should follow the conventions specified in the config.

However, it would be great to get the number of warnings raised by sass-lint down to zero!

### At the root of the repository:
1) run `npm install` to install the node modules for the project

2) run `npm run sass-lint` to see all of the current warnings and errors in the sass files

### Resolve some of the issues raised by sass-lint:

<img width="685" alt="picture 913" src="https://user-images.githubusercontent.com/8607683/29121725-a9a1acc2-7d07-11e7-9504-616205ca6723.png">

**N.B.** There are probably more than 90 warnings across many files. It is fine to **focus on just one or two files!** Smaller PRs are easier to review and ship 🚢 

### Comment here to say which files you are working on, and to ask for help

There is a pre-commit hook that will validate any staged sass files, and your commit will not complete if there are unresolved errors. You will have to completely fix a file before it can be committed.

The desired css/sass conventions would based on [guardian/frontend](https://github.com/guardian/frontend), so it may be worth looking there to see how things are done.

Message me ( @katebee ) with any questions!

**Comment by RobertFreeman** [comment]
All done, 64 sass-lint warnings resolved!
