### ISSUE TITLE
Valid test files should be provided with each native component

### ISSUE THREAD

**Issue by JonNorman** [guardian/commercial-templates#35]
It would make it a lot easier to check consistency of style and impact of CSS changes if each component had a valid `test.json` file, enabling it to be correctly rendered in preview.

In some cases, adding a blank `test.json` file will suffice, but in others it will result in failed fetches and thus a failure to correctly render.

**Comment by annebyrne** [comment]
👍

**Comment by RobertFreeman** [comment]
@JonNorman Is this still a thing you need doing? I could do with something else to practice on while I'm getting used to git...

**Comment by JonNorman** [comment]
Ah! I only just saw this! Yes absolutely!
